# Generated by Django 3.1.14 on 2024-01-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_pokemon_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='title_en',
            field=models.TextField(default='Bulbausaur'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='title_jp',
            field=models.TextField(default='フシギダネ'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default=' маленький четвероногий покемон голубовато-зелёного цвета с темно-зелёными пятнами на теле. У него красные глаза, широкий рот и слегка заострённые уши. Когда его рот открыт, на его верхней челюсти видна пара заострённых зубов. У него толстые лапы, заканчивающиеся тремя острыми когтями. На спине у Бульбазавра находится зелёная луковица, которая, согласно записи в Покедексе, была посажена там при рождении. Когда Бульбазавр готов эволюционировать, луковица на его спине начинает мерцать голубоватым цветом и впоследствии преобразуется в бутон. Если он не хочет развиваться, он изо всех сил сопротивляется трансформации.'),
        ),
    ]
