# Generated by Django 3.1.14 on 2024-01-15 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_auto_20240115_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='latttude',
            new_name='latitude',
        ),
    ]
